version: "3"

services:

  backend:
    environment:
      - SECRET_KEY='5vUCOVMkF2JNhH2CmzY4BnhDiiUtv+reNq2wwxbw31E='

      - DB_NAME=craftech

      - DB_ENGINE=postgres

      - DB_USER=craftech

      - DB_PASS=craftech

      - DB_HOST=127.0.0.1:5432

      - DB_PORT=5432
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - craftech-net
    depends_on:
      - db
  db:
    image: "postgres:13.2-alpine"
    environment:
      - POSTGRES_PASSWORD=craftech
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - craftech-net
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV:development

    networks:
      - craftech-net
volumes:
  node-modules:
networks:
  craftech-net:
