version: "3"

services:

  backend:
    environment:
      - SECRET_KEY='5vUCOVMkF2JNhH2CmzY4BnhDiiUtv+reNq2wwxbw31E='

      - DB_NAME=craftech

      - DB_ENGINE=ENDPOINT="postgresql"

      - DB_USER=craftech

      - DB_PASS=craftech

      - DB_HOST=127.0.0.1:5432

      - DB_PORT=5432
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - craftech-net
    depends_on:
      - db
  db:https://www.paypal.com/ar/webapps/mpp/withdraw-funds/nubi
    image: "postgres:13.2-alpine"
    environment:
      - POSTGRES_PASSWORD=craftech
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - craftech-net
  frontend:
    build: ./frontend
    environment:
      - ENDPOINT='http://192.168.158.128:8000/api/requests-loan/'
    ports:
      - "8080:80"
    networks:
      - craftech-net
networks:
  craftech-net:
