version: "3"

services:

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - craftech-net
  db:
    image: "postgres:13.2-alpine"
    ports:
      - "5432:5432"
    networks:
      - craftech-net
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV:development
    networks:
      - craftech-net
volumes:
  node-modules:
networks:
  craftech-net:
